# Generated by Django 5.2.3 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
